apiVersion : apps/v1
kind: Deployment
metadata:
  name: serviceaccount-deployment
  labels:
    app: serviceaccount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceaccount
  template:
    metadata:
      labels:
        app: serviceaccount 
    spec:
      containers:
        - name: serviceaccount 
          image: razvan426823wedeliver.azurecr.io/serviceaccount
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING
          ports:
          - containerPort: 80
